// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/telemetryqueryextension/query_service.proto

package telemetryqueryextension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryType defines the type of telemetry data.
type TelemetryType int32

const (
	TelemetryType_TELEMETRY_TYPE_UNSPECIFIED TelemetryType = 0
	TelemetryType_TELEMETRY_TYPE_TRACES      TelemetryType = 1
	TelemetryType_TELEMETRY_TYPE_METRICS     TelemetryType = 2
	TelemetryType_TELEMETRY_TYPE_LOGS        TelemetryType = 3
)

// Enum value maps for TelemetryType.
var (
	TelemetryType_name = map[int32]string{
		0: "TELEMETRY_TYPE_UNSPECIFIED",
		1: "TELEMETRY_TYPE_TRACES",
		2: "TELEMETRY_TYPE_METRICS",
		3: "TELEMETRY_TYPE_LOGS",
	}
	TelemetryType_value = map[string]int32{
		"TELEMETRY_TYPE_UNSPECIFIED": 0,
		"TELEMETRY_TYPE_TRACES":      1,
		"TELEMETRY_TYPE_METRICS":     2,
		"TELEMETRY_TYPE_LOGS":        3,
	}
)

func (x TelemetryType) Enum() *TelemetryType {
	p := new(TelemetryType)
	*p = x
	return p
}

func (x TelemetryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_telemetryqueryextension_query_service_proto_enumTypes[0].Descriptor()
}

func (TelemetryType) Type() protoreflect.EnumType {
	return &file_internal_telemetryqueryextension_query_service_proto_enumTypes[0]
}

func (x TelemetryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryType.Descriptor instead.
func (TelemetryType) EnumDescriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{0}
}

// QueryRequest is a request to query telemetry data from the ring buffer.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of telemetry data to query.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// Optional start time for filtering by time range.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional end time for filtering by time range.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Optional trace ID for filtering by trace.
	TraceId string `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional service name for filtering by service.
	ServiceName string `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Optional maximum number of results to return.
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *QueryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SubscribeRequest is a request to subscribe to telemetry data from the ring buffer.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of telemetry data to subscribe to.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// Optional start time for filtering by time range.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional trace ID for filtering by trace.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional service name for filtering by service.
	ServiceName   string `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *SubscribeRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SubscribeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// QueryResponse is a response containing telemetry data.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spans returned for trace queries.
	Spans []*Span `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	// Metrics returned for metric queries.
	Metrics []*MetricDataPoint `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Logs returned for log queries.
	Logs          []*LogRecord `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *QueryResponse) GetMetrics() []*MetricDataPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryResponse) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

// Span represents a trace span.
type Span struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	TraceId       string                     `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId        string                     `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ParentSpanId  string                     `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                     `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	StartTime     *timestamppb.Timestamp     `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationNanos int64                      `protobuf:"varint,8,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	StatusCode    string                     `protobuf:"bytes,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage string                     `protobuf:"bytes,10,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	ServiceName   string                     `protobuf:"bytes,11,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{3}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Span) GetDurationNanos() int64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

func (x *Span) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Span) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// LogRecord represents a log record.
type LogRecord struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	TraceId        string                     `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId         string                     `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	Timestamp      *timestamppb.Timestamp     `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SeverityText   string                     `protobuf:"bytes,4,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	SeverityNumber int32                      `protobuf:"varint,5,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	Body           string                     `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ServiceName    string                     `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Attributes     map[string]*AttributeValue `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *LogRecord) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRecord) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// MetricDataPoint represents a metric data point.
type MetricDataPoint struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Unit        string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Type        string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*MetricDataPoint_IntValue
	//	*MetricDataPoint_DoubleValue
	//	*MetricDataPoint_Count
	Value         isMetricDataPoint_Value    `protobuf_oneof:"value"`
	ServiceName   string                     `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDataPoint) Reset() {
	*x = MetricDataPoint{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataPoint) ProtoMessage() {}

func (x *MetricDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataPoint.ProtoReflect.Descriptor instead.
func (*MetricDataPoint) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{5}
}

func (x *MetricDataPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDataPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDataPoint) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricDataPoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricDataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricDataPoint) GetValue() isMetricDataPoint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricDataPoint) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetricDataPoint) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetricDataPoint) GetCount() *Count {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_Count); ok {
			return x.Count
		}
	}
	return nil
}

func (x *MetricDataPoint) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricDataPoint) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type isMetricDataPoint_Value interface {
	isMetricDataPoint_Value()
}

type MetricDataPoint_IntValue struct {
	IntValue int64 `protobuf:"varint,6,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetricDataPoint_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MetricDataPoint_Count struct {
	Count *Count `protobuf:"bytes,8,opt,name=count,proto3,oneof"`
}

func (*MetricDataPoint_IntValue) isMetricDataPoint_Value() {}

func (*MetricDataPoint_DoubleValue) isMetricDataPoint_Value() {}

func (*MetricDataPoint_Count) isMetricDataPoint_Value() {}

// Count is a simple count value.
type Count struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{6}
}

func (x *Count) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// AttributeValue represents a value of an attribute.
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_DoubleValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_ArrayValue
	//	*AttributeValue_KvlistValue
	//	*AttributeValue_BytesValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{7}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AttributeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AttributeValue) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

func (x *AttributeValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,5,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AttributeValue_KvlistValue struct {
	KvlistValue *KeyValueList `protobuf:"bytes,6,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

type AttributeValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_DoubleValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_ArrayValue) isAttributeValue_Value() {}

func (*AttributeValue_KvlistValue) isAttributeValue_Value() {}

func (*AttributeValue_BytesValue) isAttributeValue_Value() {}

// ArrayValue represents an array of values.
type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AttributeValue      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{8}
}

func (x *ArrayValue) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValueList represents a list of key-value pairs.
type KeyValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*KeyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{9}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValue represents a key-value pair.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *AttributeValue        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{10}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AttributeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// BufferInfo contains information about a ring buffer.
type BufferInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of telemetry data in the buffer.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// Current number of items in the buffer.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// Maximum capacity of the buffer.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// Oldest timestamp in the buffer.
	OldestTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=oldest_timestamp,json=oldestTimestamp,proto3" json:"oldest_timestamp,omitempty"`
	// Newest timestamp in the buffer.
	NewestTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=newest_timestamp,json=newestTimestamp,proto3" json:"newest_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BufferInfo) Reset() {
	*x = BufferInfo{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferInfo) ProtoMessage() {}

func (x *BufferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferInfo.ProtoReflect.Descriptor instead.
func (*BufferInfo) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{11}
}

func (x *BufferInfo) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *BufferInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BufferInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BufferInfo) GetOldestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestTimestamp
	}
	return nil
}

func (x *BufferInfo) GetNewestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.NewestTimestamp
	}
	return nil
}

// BufferInfoResponse contains information about all ring buffers.
type BufferInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about each buffer.
	Buffers       []*BufferInfo `protobuf:"bytes,1,rep,name=buffers,proto3" json:"buffers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferInfoResponse) Reset() {
	*x = BufferInfoResponse{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferInfoResponse) ProtoMessage() {}

func (x *BufferInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferInfoResponse.ProtoReflect.Descriptor instead.
func (*BufferInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{12}
}

func (x *BufferInfoResponse) GetBuffers() []*BufferInfo {
	if x != nil {
		return x.Buffers
	}
	return nil
}

var File_internal_telemetryqueryextension_query_service_proto protoreflect.FileDescriptor

const file_internal_telemetryqueryextension_query_service_proto_rawDesc = "" +
	"\n" +
	"4internal/telemetryqueryextension/query_service.proto\x12\x0etelemetryquery\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n" +
	"\fQueryRequest\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xd1\x01\n" +
	"\x10SubscribeRequest\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\"\xa5\x01\n" +
	"\rQueryResponse\x12*\n" +
	"\x05spans\x18\x01 \x03(\v2\x14.telemetryquery.SpanR\x05spans\x129\n" +
	"\ametrics\x18\x02 \x03(\v2\x1f.telemetryquery.MetricDataPointR\ametrics\x12-\n" +
	"\x04logs\x18\x03 \x03(\v2\x19.telemetryquery.LogRecordR\x04logs\"\xb1\x04\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12%\n" +
	"\x0eduration_nanos\x18\b \x01(\x03R\rdurationNanos\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\tR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\n" +
	" \x01(\tR\rstatusMessage\x12!\n" +
	"\fservice_name\x18\v \x01(\tR\vserviceName\x12D\n" +
	"\n" +
	"attributes\x18\f \x03(\v2$.telemetryquery.Span.AttributesEntryR\n" +
	"attributes\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01\"\xa8\x03\n" +
	"\tLogRecord\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rseverity_text\x18\x04 \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\x05 \x01(\x05R\x0eseverityNumber\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12I\n" +
	"\n" +
	"attributes\x18\b \x03(\v2).telemetryquery.LogRecord.AttributesEntryR\n" +
	"attributes\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01\"\xf8\x03\n" +
	"\x0fMetricDataPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\tint_value\x18\x06 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\a \x01(\x01H\x00R\vdoubleValue\x12-\n" +
	"\x05count\x18\b \x01(\v2\x15.telemetryquery.CountH\x00R\x05count\x12!\n" +
	"\fservice_name\x18\t \x01(\tR\vserviceName\x12O\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2/.telemetryquery.MetricDataPoint.AttributesEntryR\n" +
	"attributes\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01B\a\n" +
	"\x05value\"\x1d\n" +
	"\x05Count\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xc8\x02\n" +
	"\x0eAttributeValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12=\n" +
	"\varray_value\x18\x05 \x01(\v2\x1a.telemetryquery.ArrayValueH\x00R\n" +
	"arrayValue\x12A\n" +
	"\fkvlist_value\x18\x06 \x01(\v2\x1c.telemetryquery.KeyValueListH\x00R\vkvlistValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValueB\a\n" +
	"\x05value\"D\n" +
	"\n" +
	"ArrayValue\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.telemetryquery.AttributeValueR\x06values\"@\n" +
	"\fKeyValueList\x120\n" +
	"\x06values\x18\x01 \x03(\v2\x18.telemetryquery.KeyValueR\x06values\"R\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value\"\x90\x02\n" +
	"\n" +
	"BufferInfo\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12E\n" +
	"\x10oldest_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0foldestTimestamp\x12E\n" +
	"\x10newest_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fnewestTimestamp\"J\n" +
	"\x12BufferInfoResponse\x124\n" +
	"\abuffers\x18\x01 \x03(\v2\x1a.telemetryquery.BufferInfoR\abuffers*\x7f\n" +
	"\rTelemetryType\x12\x1e\n" +
	"\x1aTELEMETRY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TELEMETRY_TYPE_TRACES\x10\x01\x12\x1a\n" +
	"\x16TELEMETRY_TYPE_METRICS\x10\x02\x12\x17\n" +
	"\x13TELEMETRY_TYPE_LOGS\x10\x032\xfa\x01\n" +
	"\x15TelemetryQueryService\x12D\n" +
	"\x05Query\x12\x1c.telemetryquery.QueryRequest\x1a\x1d.telemetryquery.QueryResponse\x12N\n" +
	"\tSubscribe\x12 .telemetryquery.SubscribeRequest\x1a\x1d.telemetryquery.QueryResponse0\x01\x12K\n" +
	"\rGetBufferInfo\x12\x16.google.protobuf.Empty\x1a\".telemetryquery.BufferInfoResponseBGZEgithub.com/dvroom/telemetrycollector/internal/telemetryqueryextensionb\x06proto3"

var (
	file_internal_telemetryqueryextension_query_service_proto_rawDescOnce sync.Once
	file_internal_telemetryqueryextension_query_service_proto_rawDescData []byte
)

func file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP() []byte {
	file_internal_telemetryqueryextension_query_service_proto_rawDescOnce.Do(func() {
		file_internal_telemetryqueryextension_query_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_telemetryqueryextension_query_service_proto_rawDesc), len(file_internal_telemetryqueryextension_query_service_proto_rawDesc)))
	})
	return file_internal_telemetryqueryextension_query_service_proto_rawDescData
}

var file_internal_telemetryqueryextension_query_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_telemetryqueryextension_query_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_telemetryqueryextension_query_service_proto_goTypes = []any{
	(TelemetryType)(0),            // 0: telemetryquery.TelemetryType
	(*QueryRequest)(nil),          // 1: telemetryquery.QueryRequest
	(*SubscribeRequest)(nil),      // 2: telemetryquery.SubscribeRequest
	(*QueryResponse)(nil),         // 3: telemetryquery.QueryResponse
	(*Span)(nil),                  // 4: telemetryquery.Span
	(*LogRecord)(nil),             // 5: telemetryquery.LogRecord
	(*MetricDataPoint)(nil),       // 6: telemetryquery.MetricDataPoint
	(*Count)(nil),                 // 7: telemetryquery.Count
	(*AttributeValue)(nil),        // 8: telemetryquery.AttributeValue
	(*ArrayValue)(nil),            // 9: telemetryquery.ArrayValue
	(*KeyValueList)(nil),          // 10: telemetryquery.KeyValueList
	(*KeyValue)(nil),              // 11: telemetryquery.KeyValue
	(*BufferInfo)(nil),            // 12: telemetryquery.BufferInfo
	(*BufferInfoResponse)(nil),    // 13: telemetryquery.BufferInfoResponse
	nil,                           // 14: telemetryquery.Span.AttributesEntry
	nil,                           // 15: telemetryquery.LogRecord.AttributesEntry
	nil,                           // 16: telemetryquery.MetricDataPoint.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 18: google.protobuf.Empty
}
var file_internal_telemetryqueryextension_query_service_proto_depIdxs = []int32{
	0,  // 0: telemetryquery.QueryRequest.telemetry_type:type_name -> telemetryquery.TelemetryType
	17, // 1: telemetryquery.QueryRequest.start_time:type_name -> google.protobuf.Timestamp
	17, // 2: telemetryquery.QueryRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 3: telemetryquery.SubscribeRequest.telemetry_type:type_name -> telemetryquery.TelemetryType
	17, // 4: telemetryquery.SubscribeRequest.start_time:type_name -> google.protobuf.Timestamp
	4,  // 5: telemetryquery.QueryResponse.spans:type_name -> telemetryquery.Span
	6,  // 6: telemetryquery.QueryResponse.metrics:type_name -> telemetryquery.MetricDataPoint
	5,  // 7: telemetryquery.QueryResponse.logs:type_name -> telemetryquery.LogRecord
	17, // 8: telemetryquery.Span.start_time:type_name -> google.protobuf.Timestamp
	17, // 9: telemetryquery.Span.end_time:type_name -> google.protobuf.Timestamp
	14, // 10: telemetryquery.Span.attributes:type_name -> telemetryquery.Span.AttributesEntry
	17, // 11: telemetryquery.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	15, // 12: telemetryquery.LogRecord.attributes:type_name -> telemetryquery.LogRecord.AttributesEntry
	17, // 13: telemetryquery.MetricDataPoint.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 14: telemetryquery.MetricDataPoint.count:type_name -> telemetryquery.Count
	16, // 15: telemetryquery.MetricDataPoint.attributes:type_name -> telemetryquery.MetricDataPoint.AttributesEntry
	9,  // 16: telemetryquery.AttributeValue.array_value:type_name -> telemetryquery.ArrayValue
	10, // 17: telemetryquery.AttributeValue.kvlist_value:type_name -> telemetryquery.KeyValueList
	8,  // 18: telemetryquery.ArrayValue.values:type_name -> telemetryquery.AttributeValue
	11, // 19: telemetryquery.KeyValueList.values:type_name -> telemetryquery.KeyValue
	8,  // 20: telemetryquery.KeyValue.value:type_name -> telemetryquery.AttributeValue
	0,  // 21: telemetryquery.BufferInfo.telemetry_type:type_name -> telemetryquery.TelemetryType
	17, // 22: telemetryquery.BufferInfo.oldest_timestamp:type_name -> google.protobuf.Timestamp
	17, // 23: telemetryquery.BufferInfo.newest_timestamp:type_name -> google.protobuf.Timestamp
	12, // 24: telemetryquery.BufferInfoResponse.buffers:type_name -> telemetryquery.BufferInfo
	8,  // 25: telemetryquery.Span.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	8,  // 26: telemetryquery.LogRecord.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	8,  // 27: telemetryquery.MetricDataPoint.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	1,  // 28: telemetryquery.TelemetryQueryService.Query:input_type -> telemetryquery.QueryRequest
	2,  // 29: telemetryquery.TelemetryQueryService.Subscribe:input_type -> telemetryquery.SubscribeRequest
	18, // 30: telemetryquery.TelemetryQueryService.GetBufferInfo:input_type -> google.protobuf.Empty
	3,  // 31: telemetryquery.TelemetryQueryService.Query:output_type -> telemetryquery.QueryResponse
	3,  // 32: telemetryquery.TelemetryQueryService.Subscribe:output_type -> telemetryquery.QueryResponse
	13, // 33: telemetryquery.TelemetryQueryService.GetBufferInfo:output_type -> telemetryquery.BufferInfoResponse
	31, // [31:34] is the sub-list for method output_type
	28, // [28:31] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_internal_telemetryqueryextension_query_service_proto_init() }
func file_internal_telemetryqueryextension_query_service_proto_init() {
	if File_internal_telemetryqueryextension_query_service_proto != nil {
		return
	}
	file_internal_telemetryqueryextension_query_service_proto_msgTypes[5].OneofWrappers = []any{
		(*MetricDataPoint_IntValue)(nil),
		(*MetricDataPoint_DoubleValue)(nil),
		(*MetricDataPoint_Count)(nil),
	}
	file_internal_telemetryqueryextension_query_service_proto_msgTypes[7].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_DoubleValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_ArrayValue)(nil),
		(*AttributeValue_KvlistValue)(nil),
		(*AttributeValue_BytesValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_telemetryqueryextension_query_service_proto_rawDesc), len(file_internal_telemetryqueryextension_query_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_telemetryqueryextension_query_service_proto_goTypes,
		DependencyIndexes: file_internal_telemetryqueryextension_query_service_proto_depIdxs,
		EnumInfos:         file_internal_telemetryqueryextension_query_service_proto_enumTypes,
		MessageInfos:      file_internal_telemetryqueryextension_query_service_proto_msgTypes,
	}.Build()
	File_internal_telemetryqueryextension_query_service_proto = out.File
	file_internal_telemetryqueryextension_query_service_proto_goTypes = nil
	file_internal_telemetryqueryextension_query_service_proto_depIdxs = nil
}
