// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: internal/telemetryqueryextension/query_service.proto

package telemetryqueryextension

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryQueryService_Query_FullMethodName         = "/telemetryquery.TelemetryQueryService/Query"
	TelemetryQueryService_Subscribe_FullMethodName     = "/telemetryquery.TelemetryQueryService/Subscribe"
	TelemetryQueryService_GetBufferInfo_FullMethodName = "/telemetryquery.TelemetryQueryService/GetBufferInfo"
)

// TelemetryQueryServiceClient is the client API for TelemetryQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelemetryQueryService provides methods to query telemetry data from the ring buffer.
type TelemetryQueryServiceClient interface {
	// Query retrieves telemetry data from the ring buffer based on the provided filters.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Subscribe streams telemetry data from the ring buffer as it arrives.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error)
	// GetBufferInfo returns information about the ring buffers.
	GetBufferInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BufferInfoResponse, error)
}

type telemetryQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryQueryServiceClient(cc grpc.ClientConnInterface) TelemetryQueryServiceClient {
	return &telemetryQueryServiceClient{cc}
}

func (c *telemetryQueryServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, TelemetryQueryService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryQueryServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryQueryService_ServiceDesc.Streams[0], TelemetryQueryService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, QueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryQueryService_SubscribeClient = grpc.ServerStreamingClient[QueryResponse]

func (c *telemetryQueryServiceClient) GetBufferInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BufferInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BufferInfoResponse)
	err := c.cc.Invoke(ctx, TelemetryQueryService_GetBufferInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryQueryServiceServer is the server API for TelemetryQueryService service.
// All implementations must embed UnimplementedTelemetryQueryServiceServer
// for forward compatibility.
//
// TelemetryQueryService provides methods to query telemetry data from the ring buffer.
type TelemetryQueryServiceServer interface {
	// Query retrieves telemetry data from the ring buffer based on the provided filters.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Subscribe streams telemetry data from the ring buffer as it arrives.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[QueryResponse]) error
	// GetBufferInfo returns information about the ring buffers.
	GetBufferInfo(context.Context, *emptypb.Empty) (*BufferInfoResponse, error)
	mustEmbedUnimplementedTelemetryQueryServiceServer()
}

// UnimplementedTelemetryQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryQueryServiceServer struct{}

func (UnimplementedTelemetryQueryServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedTelemetryQueryServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[QueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTelemetryQueryServiceServer) GetBufferInfo(context.Context, *emptypb.Empty) (*BufferInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBufferInfo not implemented")
}
func (UnimplementedTelemetryQueryServiceServer) mustEmbedUnimplementedTelemetryQueryServiceServer() {}
func (UnimplementedTelemetryQueryServiceServer) testEmbeddedByValue()                               {}

// UnsafeTelemetryQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryQueryServiceServer will
// result in compilation errors.
type UnsafeTelemetryQueryServiceServer interface {
	mustEmbedUnimplementedTelemetryQueryServiceServer()
}

func RegisterTelemetryQueryServiceServer(s grpc.ServiceRegistrar, srv TelemetryQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryQueryService_ServiceDesc, srv)
}

func _TelemetryQueryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryQueryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryQueryService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryQueryServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryQueryService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelemetryQueryServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, QueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryQueryService_SubscribeServer = grpc.ServerStreamingServer[QueryResponse]

func _TelemetryQueryService_GetBufferInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryQueryServiceServer).GetBufferInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryQueryService_GetBufferInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryQueryServiceServer).GetBufferInfo(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryQueryService_ServiceDesc is the grpc.ServiceDesc for TelemetryQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetryquery.TelemetryQueryService",
	HandlerType: (*TelemetryQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _TelemetryQueryService_Query_Handler,
		},
		{
			MethodName: "GetBufferInfo",
			Handler:    _TelemetryQueryService_GetBufferInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TelemetryQueryService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/telemetryqueryextension/query_service.proto",
}
