// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: internal/telemetryqueryextension/query_service.proto

package telemetryqueryextension

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TelemetryType defines the type of telemetry data.
type TelemetryType int32

const (
	TelemetryType_TELEMETRY_TYPE_UNSPECIFIED TelemetryType = 0
	TelemetryType_TELEMETRY_TYPE_TRACES      TelemetryType = 1
	TelemetryType_TELEMETRY_TYPE_METRICS     TelemetryType = 2
	TelemetryType_TELEMETRY_TYPE_LOGS        TelemetryType = 3
)

// Enum value maps for TelemetryType.
var (
	TelemetryType_name = map[int32]string{
		0: "TELEMETRY_TYPE_UNSPECIFIED",
		1: "TELEMETRY_TYPE_TRACES",
		2: "TELEMETRY_TYPE_METRICS",
		3: "TELEMETRY_TYPE_LOGS",
	}
	TelemetryType_value = map[string]int32{
		"TELEMETRY_TYPE_UNSPECIFIED": 0,
		"TELEMETRY_TYPE_TRACES":      1,
		"TELEMETRY_TYPE_METRICS":     2,
		"TELEMETRY_TYPE_LOGS":        3,
	}
)

func (x TelemetryType) Enum() *TelemetryType {
	p := new(TelemetryType)
	*p = x
	return p
}

func (x TelemetryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_telemetryqueryextension_query_service_proto_enumTypes[0].Descriptor()
}

func (TelemetryType) Type() protoreflect.EnumType {
	return &file_internal_telemetryqueryextension_query_service_proto_enumTypes[0]
}

func (x TelemetryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryType.Descriptor instead.
func (TelemetryType) EnumDescriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{0}
}

// QueryRequest is a request to query telemetry data from the ring buffer.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of telemetry data to query.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// Optional trace ID to filter by.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional service name to filter by.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Optional start time to filter by.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Optional end time to filter by.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Optional limit on the number of results to return.
	Limit         int32 `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *QueryRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *QueryRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *QueryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SubscribeRequest is a request to subscribe to telemetry data from the ring buffer.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of telemetry data to subscribe to.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// Optional trace ID to filter by.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Optional service name to filter by.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Optional start time to filter by.
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *SubscribeRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SubscribeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SubscribeRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

// QueryResponse contains the telemetry data that matches the query.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Spans matching the query.
	Spans []*Span `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	// Metrics matching the query.
	Metrics []*MetricDataPoint `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// Logs matching the query.
	Logs          []*LogRecord `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryResponse) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *QueryResponse) GetMetrics() []*MetricDataPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryResponse) GetLogs() []*LogRecord {
	if x != nil {
		return x.Logs
	}
	return nil
}

// BufferInfoResponse contains information about the ring buffers.
type BufferInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Information about each buffer.
	Buffers       []*BufferInfo `protobuf:"bytes,1,rep,name=buffers,proto3" json:"buffers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferInfoResponse) Reset() {
	*x = BufferInfoResponse{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferInfoResponse) ProtoMessage() {}

func (x *BufferInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferInfoResponse.ProtoReflect.Descriptor instead.
func (*BufferInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{3}
}

func (x *BufferInfoResponse) GetBuffers() []*BufferInfo {
	if x != nil {
		return x.Buffers
	}
	return nil
}

// BufferInfo contains information about a ring buffer.
type BufferInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of telemetry data in the buffer.
	TelemetryType TelemetryType `protobuf:"varint,1,opt,name=telemetry_type,json=telemetryType,proto3,enum=telemetryquery.TelemetryType" json:"telemetry_type,omitempty"`
	// The current size of the buffer.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// The capacity of the buffer.
	Capacity int32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// The oldest timestamp in the buffer.
	OldestTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=oldest_timestamp,json=oldestTimestamp,proto3" json:"oldest_timestamp,omitempty"`
	// The newest timestamp in the buffer.
	NewestTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=newest_timestamp,json=newestTimestamp,proto3" json:"newest_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BufferInfo) Reset() {
	*x = BufferInfo{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferInfo) ProtoMessage() {}

func (x *BufferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferInfo.ProtoReflect.Descriptor instead.
func (*BufferInfo) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{4}
}

func (x *BufferInfo) GetTelemetryType() TelemetryType {
	if x != nil {
		return x.TelemetryType
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

func (x *BufferInfo) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BufferInfo) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *BufferInfo) GetOldestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.OldestTimestamp
	}
	return nil
}

func (x *BufferInfo) GetNewestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.NewestTimestamp
	}
	return nil
}

// Span represents a trace span.
type Span struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The trace ID.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// The span ID.
	SpanId string `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// The parent span ID.
	ParentSpanId string `protobuf:"bytes,3,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// The name of the span.
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// The kind of span.
	Kind string `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	// The start time of the span.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// The end time of the span.
	EndTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// The duration of the span in nanoseconds.
	DurationNanos int64 `protobuf:"varint,8,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	// The status code of the span.
	StatusCode string `protobuf:"bytes,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// The status message of the span.
	StatusMessage string `protobuf:"bytes,10,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	// The service name.
	ServiceName string `protobuf:"bytes,11,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// The attributes of the span.
	Attributes    map[string]*AttributeValue `protobuf:"bytes,12,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{5}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetParentSpanId() string {
	if x != nil {
		return x.ParentSpanId
	}
	return ""
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Span) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Span) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Span) GetDurationNanos() int64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

func (x *Span) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *Span) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// MetricDataPoint represents a metric data point.
type MetricDataPoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the metric.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the metric.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The unit of the metric.
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// The type of the metric.
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// The timestamp of the metric.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The service name.
	ServiceName string `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// The attributes of the metric.
	Attributes map[string]*AttributeValue `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The value of the metric.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*MetricDataPoint_IntValue
	//	*MetricDataPoint_DoubleValue
	//	*MetricDataPoint_Count
	//	*MetricDataPoint_Histogram
	Value         isMetricDataPoint_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDataPoint) Reset() {
	*x = MetricDataPoint{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataPoint) ProtoMessage() {}

func (x *MetricDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataPoint.ProtoReflect.Descriptor instead.
func (*MetricDataPoint) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{6}
}

func (x *MetricDataPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricDataPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDataPoint) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *MetricDataPoint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricDataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricDataPoint) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *MetricDataPoint) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *MetricDataPoint) GetValue() isMetricDataPoint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *MetricDataPoint) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *MetricDataPoint) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *MetricDataPoint) GetCount() *Count {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_Count); ok {
			return x.Count
		}
	}
	return nil
}

func (x *MetricDataPoint) GetHistogram() *Histogram {
	if x != nil {
		if x, ok := x.Value.(*MetricDataPoint_Histogram); ok {
			return x.Histogram
		}
	}
	return nil
}

type isMetricDataPoint_Value interface {
	isMetricDataPoint_Value()
}

type MetricDataPoint_IntValue struct {
	// The integer value.
	IntValue int64 `protobuf:"varint,8,opt,name=int_value,json=intValue,proto3,oneof"`
}

type MetricDataPoint_DoubleValue struct {
	// The double value.
	DoubleValue float64 `protobuf:"fixed64,9,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type MetricDataPoint_Count struct {
	// The count value.
	Count *Count `protobuf:"bytes,10,opt,name=count,proto3,oneof"`
}

type MetricDataPoint_Histogram struct {
	// The histogram value.
	Histogram *Histogram `protobuf:"bytes,11,opt,name=histogram,proto3,oneof"`
}

func (*MetricDataPoint_IntValue) isMetricDataPoint_Value() {}

func (*MetricDataPoint_DoubleValue) isMetricDataPoint_Value() {}

func (*MetricDataPoint_Count) isMetricDataPoint_Value() {}

func (*MetricDataPoint_Histogram) isMetricDataPoint_Value() {}

// Count represents a count value.
type Count struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The count value.
	Count         int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Count) Reset() {
	*x = Count{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Count) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Count) ProtoMessage() {}

func (x *Count) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Count.ProtoReflect.Descriptor instead.
func (*Count) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{7}
}

func (x *Count) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// Histogram represents a histogram value.
type Histogram struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The count of values in the histogram.
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// The sum of values in the histogram.
	Sum float64 `protobuf:"fixed64,2,opt,name=sum,proto3" json:"sum,omitempty"`
	// The buckets of the histogram.
	Buckets       []*HistogramBucket `protobuf:"bytes,3,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Histogram) Reset() {
	*x = Histogram{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Histogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Histogram) ProtoMessage() {}

func (x *Histogram) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Histogram.ProtoReflect.Descriptor instead.
func (*Histogram) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{8}
}

func (x *Histogram) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Histogram) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *Histogram) GetBuckets() []*HistogramBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

// HistogramBucket represents a bucket in a histogram.
type HistogramBucket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The count of values in the bucket.
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// The upper bound of the bucket.
	UpperBound    float64 `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound,proto3" json:"upper_bound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistogramBucket) Reset() {
	*x = HistogramBucket{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistogramBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistogramBucket) ProtoMessage() {}

func (x *HistogramBucket) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistogramBucket.ProtoReflect.Descriptor instead.
func (*HistogramBucket) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{9}
}

func (x *HistogramBucket) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HistogramBucket) GetUpperBound() float64 {
	if x != nil {
		return x.UpperBound
	}
	return 0
}

// LogRecord represents a log record.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The trace ID.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// The span ID.
	SpanId string `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// The timestamp of the log.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The severity text of the log.
	SeverityText string `protobuf:"bytes,4,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	// The severity number of the log.
	SeverityNumber int32 `protobuf:"varint,5,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	// The body of the log.
	Body string `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	// The service name.
	ServiceName string `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// The attributes of the log.
	Attributes    map[string]*AttributeValue `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{10}
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *LogRecord) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogRecord) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// AttributeValue represents a value of an attribute.
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value of the attribute.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*AttributeValue_StringValue
	//	*AttributeValue_IntValue
	//	*AttributeValue_DoubleValue
	//	*AttributeValue_BoolValue
	//	*AttributeValue_BytesValue
	//	*AttributeValue_ArrayValue
	//	*AttributeValue_KvlistValue
	Value         isAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{11}
}

func (x *AttributeValue) GetValue() isAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AttributeValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AttributeValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AttributeValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AttributeValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *AttributeValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AttributeValue) GetKvlistValue() *KeyValueList {
	if x != nil {
		if x, ok := x.Value.(*AttributeValue_KvlistValue); ok {
			return x.KvlistValue
		}
	}
	return nil
}

type isAttributeValue_Value interface {
	isAttributeValue_Value()
}

type AttributeValue_StringValue struct {
	// The string value.
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AttributeValue_IntValue struct {
	// The integer value.
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AttributeValue_DoubleValue struct {
	// The double value.
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	// The boolean value.
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AttributeValue_BytesValue struct {
	// The bytes value.
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type AttributeValue_ArrayValue struct {
	// The array value.
	ArrayValue *ArrayValue `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AttributeValue_KvlistValue struct {
	// The key-value list value.
	KvlistValue *KeyValueList `protobuf:"bytes,7,opt,name=kvlist_value,json=kvlistValue,proto3,oneof"`
}

func (*AttributeValue_StringValue) isAttributeValue_Value() {}

func (*AttributeValue_IntValue) isAttributeValue_Value() {}

func (*AttributeValue_DoubleValue) isAttributeValue_Value() {}

func (*AttributeValue_BoolValue) isAttributeValue_Value() {}

func (*AttributeValue_BytesValue) isAttributeValue_Value() {}

func (*AttributeValue_ArrayValue) isAttributeValue_Value() {}

func (*AttributeValue_KvlistValue) isAttributeValue_Value() {}

// ArrayValue represents an array of values.
type ArrayValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The values in the array.
	Values        []*AttributeValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{12}
}

func (x *ArrayValue) GetValues() []*AttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValueList represents a list of key-value pairs.
type KeyValueList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key-value pairs in the list.
	Values        []*KeyValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueList) Reset() {
	*x = KeyValueList{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueList) ProtoMessage() {}

func (x *KeyValueList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueList.ProtoReflect.Descriptor instead.
func (*KeyValueList) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{13}
}

func (x *KeyValueList) GetValues() []*KeyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// KeyValue represents a key-value pair.
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The value.
	Value         *AttributeValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_internal_telemetryqueryextension_query_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP(), []int{14}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AttributeValue {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_internal_telemetryqueryextension_query_service_proto protoreflect.FileDescriptor

const file_internal_telemetryqueryextension_query_service_proto_rawDesc = "" +
	"\n" +
	"4internal/telemetryqueryextension/query_service.proto\x12\x0etelemetryquery\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9a\x02\n" +
	"\fQueryRequest\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xd1\x01\n" +
	"\x10SubscribeRequest\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\"\xa5\x01\n" +
	"\rQueryResponse\x12*\n" +
	"\x05spans\x18\x01 \x03(\v2\x14.telemetryquery.SpanR\x05spans\x129\n" +
	"\ametrics\x18\x02 \x03(\v2\x1f.telemetryquery.MetricDataPointR\ametrics\x12-\n" +
	"\x04logs\x18\x03 \x03(\v2\x19.telemetryquery.LogRecordR\x04logs\"J\n" +
	"\x12BufferInfoResponse\x124\n" +
	"\abuffers\x18\x01 \x03(\v2\x1a.telemetryquery.BufferInfoR\abuffers\"\x90\x02\n" +
	"\n" +
	"BufferInfo\x12D\n" +
	"\x0etelemetry_type\x18\x01 \x01(\x0e2\x1d.telemetryquery.TelemetryTypeR\rtelemetryType\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12E\n" +
	"\x10oldest_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0foldestTimestamp\x12E\n" +
	"\x10newest_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fnewestTimestamp\"\xb1\x04\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x03 \x01(\tR\fparentSpanId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12%\n" +
	"\x0eduration_nanos\x18\b \x01(\x03R\rdurationNanos\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\tR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\n" +
	" \x01(\tR\rstatusMessage\x12!\n" +
	"\fservice_name\x18\v \x01(\tR\vserviceName\x12D\n" +
	"\n" +
	"attributes\x18\f \x03(\v2$.telemetryquery.Span.AttributesEntryR\n" +
	"attributes\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01\"\xb3\x04\n" +
	"\x0fMetricDataPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12O\n" +
	"\n" +
	"attributes\x18\a \x03(\v2/.telemetryquery.MetricDataPoint.AttributesEntryR\n" +
	"attributes\x12\x1d\n" +
	"\tint_value\x18\b \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\t \x01(\x01H\x00R\vdoubleValue\x12-\n" +
	"\x05count\x18\n" +
	" \x01(\v2\x15.telemetryquery.CountH\x00R\x05count\x129\n" +
	"\thistogram\x18\v \x01(\v2\x19.telemetryquery.HistogramH\x00R\thistogram\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01B\a\n" +
	"\x05value\"\x1d\n" +
	"\x05Count\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"n\n" +
	"\tHistogram\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x10\n" +
	"\x03sum\x18\x02 \x01(\x01R\x03sum\x129\n" +
	"\abuckets\x18\x03 \x03(\v2\x1f.telemetryquery.HistogramBucketR\abuckets\"H\n" +
	"\x0fHistogramBucket\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\x12\x1f\n" +
	"\vupper_bound\x18\x02 \x01(\x01R\n" +
	"upperBound\"\xa8\x03\n" +
	"\tLogRecord\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\rseverity_text\x18\x04 \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\x05 \x01(\x05R\x0eseverityNumber\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12I\n" +
	"\n" +
	"attributes\x18\b \x03(\v2).telemetryquery.LogRecord.AttributesEntryR\n" +
	"attributes\x1a]\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value:\x028\x01\"\xc8\x02\n" +
	"\x0eAttributeValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12=\n" +
	"\varray_value\x18\x06 \x01(\v2\x1a.telemetryquery.ArrayValueH\x00R\n" +
	"arrayValue\x12A\n" +
	"\fkvlist_value\x18\a \x01(\v2\x1c.telemetryquery.KeyValueListH\x00R\vkvlistValueB\a\n" +
	"\x05value\"D\n" +
	"\n" +
	"ArrayValue\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.telemetryquery.AttributeValueR\x06values\"@\n" +
	"\fKeyValueList\x120\n" +
	"\x06values\x18\x01 \x03(\v2\x18.telemetryquery.KeyValueR\x06values\"R\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.telemetryquery.AttributeValueR\x05value*\x7f\n" +
	"\rTelemetryType\x12\x1e\n" +
	"\x1aTELEMETRY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TELEMETRY_TYPE_TRACES\x10\x01\x12\x1a\n" +
	"\x16TELEMETRY_TYPE_METRICS\x10\x02\x12\x17\n" +
	"\x13TELEMETRY_TYPE_LOGS\x10\x032\xfa\x01\n" +
	"\x15TelemetryQueryService\x12D\n" +
	"\x05Query\x12\x1c.telemetryquery.QueryRequest\x1a\x1d.telemetryquery.QueryResponse\x12N\n" +
	"\tSubscribe\x12 .telemetryquery.SubscribeRequest\x1a\x1d.telemetryquery.QueryResponse0\x01\x12K\n" +
	"\rGetBufferInfo\x12\x16.google.protobuf.Empty\x1a\".telemetryquery.BufferInfoResponseB5Z3telemetrycollector/internal/telemetryqueryextensionb\x06proto3"

var (
	file_internal_telemetryqueryextension_query_service_proto_rawDescOnce sync.Once
	file_internal_telemetryqueryextension_query_service_proto_rawDescData []byte
)

func file_internal_telemetryqueryextension_query_service_proto_rawDescGZIP() []byte {
	file_internal_telemetryqueryextension_query_service_proto_rawDescOnce.Do(func() {
		file_internal_telemetryqueryextension_query_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_telemetryqueryextension_query_service_proto_rawDesc), len(file_internal_telemetryqueryextension_query_service_proto_rawDesc)))
	})
	return file_internal_telemetryqueryextension_query_service_proto_rawDescData
}

var file_internal_telemetryqueryextension_query_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_telemetryqueryextension_query_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_telemetryqueryextension_query_service_proto_goTypes = []any{
	(TelemetryType)(0),            // 0: telemetryquery.TelemetryType
	(*QueryRequest)(nil),          // 1: telemetryquery.QueryRequest
	(*SubscribeRequest)(nil),      // 2: telemetryquery.SubscribeRequest
	(*QueryResponse)(nil),         // 3: telemetryquery.QueryResponse
	(*BufferInfoResponse)(nil),    // 4: telemetryquery.BufferInfoResponse
	(*BufferInfo)(nil),            // 5: telemetryquery.BufferInfo
	(*Span)(nil),                  // 6: telemetryquery.Span
	(*MetricDataPoint)(nil),       // 7: telemetryquery.MetricDataPoint
	(*Count)(nil),                 // 8: telemetryquery.Count
	(*Histogram)(nil),             // 9: telemetryquery.Histogram
	(*HistogramBucket)(nil),       // 10: telemetryquery.HistogramBucket
	(*LogRecord)(nil),             // 11: telemetryquery.LogRecord
	(*AttributeValue)(nil),        // 12: telemetryquery.AttributeValue
	(*ArrayValue)(nil),            // 13: telemetryquery.ArrayValue
	(*KeyValueList)(nil),          // 14: telemetryquery.KeyValueList
	(*KeyValue)(nil),              // 15: telemetryquery.KeyValue
	nil,                           // 16: telemetryquery.Span.AttributesEntry
	nil,                           // 17: telemetryquery.MetricDataPoint.AttributesEntry
	nil,                           // 18: telemetryquery.LogRecord.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 20: google.protobuf.Empty
}
var file_internal_telemetryqueryextension_query_service_proto_depIdxs = []int32{
	0,  // 0: telemetryquery.QueryRequest.telemetry_type:type_name -> telemetryquery.TelemetryType
	19, // 1: telemetryquery.QueryRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 2: telemetryquery.QueryRequest.end_time:type_name -> google.protobuf.Timestamp
	0,  // 3: telemetryquery.SubscribeRequest.telemetry_type:type_name -> telemetryquery.TelemetryType
	19, // 4: telemetryquery.SubscribeRequest.start_time:type_name -> google.protobuf.Timestamp
	6,  // 5: telemetryquery.QueryResponse.spans:type_name -> telemetryquery.Span
	7,  // 6: telemetryquery.QueryResponse.metrics:type_name -> telemetryquery.MetricDataPoint
	11, // 7: telemetryquery.QueryResponse.logs:type_name -> telemetryquery.LogRecord
	5,  // 8: telemetryquery.BufferInfoResponse.buffers:type_name -> telemetryquery.BufferInfo
	0,  // 9: telemetryquery.BufferInfo.telemetry_type:type_name -> telemetryquery.TelemetryType
	19, // 10: telemetryquery.BufferInfo.oldest_timestamp:type_name -> google.protobuf.Timestamp
	19, // 11: telemetryquery.BufferInfo.newest_timestamp:type_name -> google.protobuf.Timestamp
	19, // 12: telemetryquery.Span.start_time:type_name -> google.protobuf.Timestamp
	19, // 13: telemetryquery.Span.end_time:type_name -> google.protobuf.Timestamp
	16, // 14: telemetryquery.Span.attributes:type_name -> telemetryquery.Span.AttributesEntry
	19, // 15: telemetryquery.MetricDataPoint.timestamp:type_name -> google.protobuf.Timestamp
	17, // 16: telemetryquery.MetricDataPoint.attributes:type_name -> telemetryquery.MetricDataPoint.AttributesEntry
	8,  // 17: telemetryquery.MetricDataPoint.count:type_name -> telemetryquery.Count
	9,  // 18: telemetryquery.MetricDataPoint.histogram:type_name -> telemetryquery.Histogram
	10, // 19: telemetryquery.Histogram.buckets:type_name -> telemetryquery.HistogramBucket
	19, // 20: telemetryquery.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	18, // 21: telemetryquery.LogRecord.attributes:type_name -> telemetryquery.LogRecord.AttributesEntry
	13, // 22: telemetryquery.AttributeValue.array_value:type_name -> telemetryquery.ArrayValue
	14, // 23: telemetryquery.AttributeValue.kvlist_value:type_name -> telemetryquery.KeyValueList
	12, // 24: telemetryquery.ArrayValue.values:type_name -> telemetryquery.AttributeValue
	15, // 25: telemetryquery.KeyValueList.values:type_name -> telemetryquery.KeyValue
	12, // 26: telemetryquery.KeyValue.value:type_name -> telemetryquery.AttributeValue
	12, // 27: telemetryquery.Span.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	12, // 28: telemetryquery.MetricDataPoint.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	12, // 29: telemetryquery.LogRecord.AttributesEntry.value:type_name -> telemetryquery.AttributeValue
	1,  // 30: telemetryquery.TelemetryQueryService.Query:input_type -> telemetryquery.QueryRequest
	2,  // 31: telemetryquery.TelemetryQueryService.Subscribe:input_type -> telemetryquery.SubscribeRequest
	20, // 32: telemetryquery.TelemetryQueryService.GetBufferInfo:input_type -> google.protobuf.Empty
	3,  // 33: telemetryquery.TelemetryQueryService.Query:output_type -> telemetryquery.QueryResponse
	3,  // 34: telemetryquery.TelemetryQueryService.Subscribe:output_type -> telemetryquery.QueryResponse
	4,  // 35: telemetryquery.TelemetryQueryService.GetBufferInfo:output_type -> telemetryquery.BufferInfoResponse
	33, // [33:36] is the sub-list for method output_type
	30, // [30:33] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_internal_telemetryqueryextension_query_service_proto_init() }
func file_internal_telemetryqueryextension_query_service_proto_init() {
	if File_internal_telemetryqueryextension_query_service_proto != nil {
		return
	}
	file_internal_telemetryqueryextension_query_service_proto_msgTypes[6].OneofWrappers = []any{
		(*MetricDataPoint_IntValue)(nil),
		(*MetricDataPoint_DoubleValue)(nil),
		(*MetricDataPoint_Count)(nil),
		(*MetricDataPoint_Histogram)(nil),
	}
	file_internal_telemetryqueryextension_query_service_proto_msgTypes[11].OneofWrappers = []any{
		(*AttributeValue_StringValue)(nil),
		(*AttributeValue_IntValue)(nil),
		(*AttributeValue_DoubleValue)(nil),
		(*AttributeValue_BoolValue)(nil),
		(*AttributeValue_BytesValue)(nil),
		(*AttributeValue_ArrayValue)(nil),
		(*AttributeValue_KvlistValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_telemetryqueryextension_query_service_proto_rawDesc), len(file_internal_telemetryqueryextension_query_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_telemetryqueryextension_query_service_proto_goTypes,
		DependencyIndexes: file_internal_telemetryqueryextension_query_service_proto_depIdxs,
		EnumInfos:         file_internal_telemetryqueryextension_query_service_proto_enumTypes,
		MessageInfos:      file_internal_telemetryqueryextension_query_service_proto_msgTypes,
	}.Build()
	File_internal_telemetryqueryextension_query_service_proto = out.File
	file_internal_telemetryqueryextension_query_service_proto_goTypes = nil
	file_internal_telemetryqueryextension_query_service_proto_depIdxs = nil
}
